"""
This file contains all the settings/constants for the game.
"""

# Sizes
GRID_SIZE = 16
WIDTH, HEIGHT = GRID_SIZE * 60, (GRID_SIZE - 4) * 60
CELL_SIZE = WIDTH // GRID_SIZE

# Background and color information
FONT_COLOR = (0, 0, 0)
INFO_AREA_HEIGHT = 90
INFO_BG_COLOR = (230, 230, 230)

# Bools
PLACING_PIECES = 0
GAME_STARTED = 1

# Influence parameters
ALLY_INFLUENCE_STRENGTH = 0.7
ENEMY_INFLUENCE_STRENGTH = -0.9
ALLY_DECAY_FACTOR = 0.05
ENEMY_DECAY_FACTOR = 0.07
ALLY_MAX_INFLUENCE_DISTANCE = 8
ENEMY_MAX_INFLUENCE_DISTANCE = 10
